/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Authentication (void);
GtkWidget* create_Espace_Administrateur (void);
GtkWidget* create_Ajouter_un_Utilisateur (void);
GtkWidget* create_Modifier_un_Utilisateur_ (void);
GtkWidget* create_Supprimer_un_Utilisateur (void);
GtkWidget* create_Gestion_des_Utilisateurs (void);
GtkWidget* create_Espace_Electeur (void);
GtkWidget* create_Ajouter_une_Election (void);
GtkWidget* create_Modifier_une_Election (void);
GtkWidget* create_Supprimer_une_Election (void);
GtkWidget* create_Gestion_des_Elections (void);
GtkWidget* create_Ajouter_un_Bureau_de_vote (void);
GtkWidget* create_Modifier_un_Bureau_de_vote (void);
GtkWidget* create_Supprimer_un_Bureau_de_vote (void);
GtkWidget* create_Gestion_des_Bureaux_de_vote (void);
GtkWidget* create_Ajouter_une_Liste_Electorale (void);
GtkWidget* create_Modifier_une_Liste_Electorale (void);
GtkWidget* create_Supprimer_une_Liste_Electorale (void);
GtkWidget* create_Gestion_des_Listes_Electorales (void);
GtkWidget* create_Espace_Observateur (void);
GtkWidget* create_Ajouter_une_Reclamation (void);
GtkWidget* create_Modifier_une_Reclamation (void);
GtkWidget* create_Supprimer_une_Reclamation (void);
GtkWidget* create_Gestion_des_Reclamations (void);
