/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Authetication;
  GtkWidget *Espace_Administrateur;
  GtkWidget *Ajouter_un_Utilisateur;
  GtkWidget *Modifier_un_Utilisateur_;
  GtkWidget *Supprimer_un_Utilisateur;
  GtkWidget *Gestion_des_Utilisateurs;
  GtkWidget *Espace_Electeur;
  GtkWidget *Ajouter_une_Election;
  GtkWidget *Modifier_une_Election;
  GtkWidget *Supprimer_une_Election;
  GtkWidget *Gestion_des_Election;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Authetication = create_Authetication ();
  gtk_widget_show (Authetication);
  Espace_Administrateur = create_Espace_Administrateur ();
  gtk_widget_show (Espace_Administrateur);
  Ajouter_un_Utilisateur = create_Ajouter_un_Utilisateur ();
  gtk_widget_show (Ajouter_un_Utilisateur);
  Modifier_un_Utilisateur_ = create_Modifier_un_Utilisateur_ ();
  gtk_widget_show (Modifier_un_Utilisateur_);
  Supprimer_un_Utilisateur = create_Supprimer_un_Utilisateur ();
  gtk_widget_show (Supprimer_un_Utilisateur);
  Gestion_des_Utilisateurs = create_Gestion_des_Utilisateurs ();
  gtk_widget_show (Gestion_des_Utilisateurs);
  Espace_Electeur = create_Espace_Electeur ();
  gtk_widget_show (Espace_Electeur);
  Ajouter_une_Election = create_Ajouter_une_Election ();
  gtk_widget_show (Ajouter_une_Election);
  Modifier_une_Election = create_Modifier_une_Election ();
  gtk_widget_show (Modifier_une_Election);
  Supprimer_une_Election = create_Supprimer_une_Election ();
  gtk_widget_show (Supprimer_une_Election);
  Gestion_des_Election = create_Gestion_des_Election ();
  gtk_widget_show (Gestion_des_Election);

  gtk_main ();
  return 0;
}

